-- 用途：现有数据库修复——把 pte_practice_items 内置题目中的中文题干、选项、
-- SWT 题目要求和 Describe Image 图表文字改为英文，与 app/pte-practice/lib/questionBank.ts 保持一致。
-- 适用：已经执行过 database/migrations/pte-practice-items-table.sql 的数据库
-- （新数据库执行更新后的迁移即可直接得到英文题目，无需本文件，重复执行也无害）。
--
-- 影响范围：只 UPDATE 固定 id 的内置题目 payload 中被翻译的字段，
-- 使用 jsonb || 合并，不改动其它字段、不删除任何行。每条语句都带
-- "payload 仍含中文" 的条件，已经是英文或被手动改过的行不会被覆盖，可安全重复执行。
-- 依赖：无，可独立于 pte-practice-custom-items.sql 执行。
-- 备份：执行前可在 Supabase 导出 pte_practice_items 表；如需恢复，重新导入该备份即可。
-- 本文件由翻译映射脚本生成，共 107 条 UPDATE。

BEGIN;

UPDATE pte_practice_items SET payload = payload || '{"question":"According to the passage, what is the main concern of people who oppose urban beekeeping?","options":["Bees may attack pedestrians","Untrained hobbyists may spread disease and increase competition between colonies for resources","Rooftop hives may damage building structures","There are no flowers at all in cities for bees to feed on"]}'::jsonb
  WHERE id = 'r-mcq-1' AND task_type = 'reading-mcq-single' AND payload::text ~ '[\u4e00-\u9fff]';
UPDATE pte_practice_items SET payload = payload || '{"question":"What is the main purpose of companies requiring fixed in-office days each week?","options":["To reduce office rental costs","To reduce employees'' flexibility","To preserve opportunities for spontaneous collaboration that video calls rarely replicate","To monitor employees'' working hours"]}'::jsonb
  WHERE id = 'r-mcq-2' AND task_type = 'reading-mcq-single' AND payload::text ~ '[\u4e00-\u9fff]';
UPDATE pte_practice_items SET payload = payload || '{"question":"Which crops are currently grown in vertical farms at scale, and why?","options":["Staple grains, because they produce the highest yields","High-value leafy greens and herbs, because they can offset the high upfront costs","Any crop, because costs are already low","Only ornamental plants"]}'::jsonb
  WHERE id = 'r-mcq-3' AND task_type = 'reading-mcq-single' AND payload::text ~ '[\u4e00-\u9fff]';
UPDATE pte_practice_items SET payload = payload || '{"question":"What is the researchers'' attitude toward the survey findings?","options":["They fully accept that reading reduces stress","They believe checking work email is the real source of stress","They are cautious, noting that explanations other than cause and effect may exist","They believe the way people commute is unrelated to stress"]}'::jsonb
  WHERE id = 'r-mcq-4' AND task_type = 'reading-mcq-single' AND payload::text ~ '[\u4e00-\u9fff]';
UPDATE pte_practice_items SET payload = payload || '{"question":"What are some curators concerned about?","options":["Taking photos may damage the artworks","Social media promotion is ineffective","Visitors may engage less with the works themselves because they are busy taking photos","Museum ticket revenue may fall"]}'::jsonb
  WHERE id = 'r-mcq-5' AND task_type = 'reading-mcq-single' AND payload::text ~ '[\u4e00-\u9fff]';
UPDATE pte_practice_items SET payload = payload || '{"question":"What measures have some local governments taken?","options":["Banning electric scooters completely","Introducing speed limits and mandatory helmet rules in designated zones","Abolishing all traffic rules","Allowing only tourists to use scooters"]}'::jsonb
  WHERE id = 'r-mcq-6' AND task_type = 'reading-mcq-single' AND payload::text ~ '[\u4e00-\u9fff]';
UPDATE pte_practice_items SET payload = payload || '{"question":"What has cognitive research found?","options":["Multitasking is always more efficient","Switching between tasks has costs in time and accuracy","The human brain cannot handle any task switching","Focusing on a single task is actually slower"]}'::jsonb
  WHERE id = 'r-mcq-7' AND task_type = 'reading-mcq-single' AND payload::text ~ '[\u4e00-\u9fff]';
UPDATE pte_practice_items SET payload = payload || '{"question":"How do employers view micro-credentials?","options":["They unanimously consider them worthless","Opinions are divided: some value the targeted skills, while others still prefer full degrees","They unanimously consider them more important than degrees","Employers were not surveyed at all"]}'::jsonb
  WHERE id = 'r-mcq-8' AND task_type = 'reading-mcq-single' AND payload::text ~ '[\u4e00-\u9fff]';
UPDATE pte_practice_items SET payload = payload || '{"question":"According to historians, what was the real engineering achievement of the Apollo program?","options":["The images of the moon landing itself","The willingness to expose flaws early through cheap, frequent unmanned tests","Having the most advanced rocket engines of the time","Never experiencing any failures"]}'::jsonb
  WHERE id = 'r-mcq-9' AND task_type = 'reading-mcq-single' AND payload::text ~ '[\u4e00-\u9fff]';
UPDATE pte_practice_items SET payload = payload || '{"question":"What does the longitudinal workplace data reveal?","options":["Older employees are completely unable to learn new technology","Older employees learn quickly at first but soon forget","Younger employees learn faster at first, but older employees catch up within a few months and retain the skills better","There is no data on whether age affects skill learning"]}'::jsonb
  WHERE id = 'r-mcq-10' AND task_type = 'reading-mcq-single' AND payload::text ~ '[\u4e00-\u9fff]';
UPDATE pte_practice_items SET payload = payload || '{"question":"Why are soil scientists reconsidering traditional crop rotation?","options":["It produces higher yields of a single crop","It naturally suppresses pests and replenishes nitrogen, potentially reducing fertilizer use","It is faster than industrial farming","It requires no human labour at all"]}'::jsonb
  WHERE id = 'r-mcq-11' AND task_type = 'reading-mcq-single' AND payload::text ~ '[\u4e00-\u9fff]';
UPDATE pte_practice_items SET payload = payload || '{"question":"According to cognitive-behavioural researchers, what partly causes public speaking anxiety?","options":["Audiences are generally very harsh","People overestimate how much the audience notices their small mistakes, known as the \"spotlight effect\"","Speakers naturally lack language ability","Anxiety has nothing to do with audience size"]}'::jsonb
  WHERE id = 'r-mcq-12' AND task_type = 'reading-mcq-single' AND payload::text ~ '[\u4e00-\u9fff]';
UPDATE pte_practice_items SET payload = payload || '{"question":"What are some analysts concerned about?","options":["There are too few streaming platforms","The growing number of subscription platforms fragments content, which may bring back inconvenience and encourage piracy","All viewers have completely abandoned legal platforms","Piracy has disappeared completely"]}'::jsonb
  WHERE id = 'r-mcq-13' AND task_type = 'reading-mcq-single' AND payload::text ~ '[\u4e00-\u9fff]';
UPDATE pte_practice_items SET payload = payload || '{"question":"What hypothesis have archaeologists proposed based on this?","options":["The settlement''s population was far larger than expected","The settlement may have been a regional trading hub rather than a self-sufficient village","The size of the granaries was simply a construction error","The settlement never stored grain"]}'::jsonb
  WHERE id = 'r-mcq-14' AND task_type = 'reading-mcq-single' AND payload::text ~ '[\u4e00-\u9fff]';
UPDATE pte_practice_items SET payload = payload || '{"question":"Which type of sound are noise-cancelling headphones less effective against?","options":["Low, constant engine noise","Sudden, unpredictable sounds such as a dog barking","They are equally effective against all types of sound","They do not reduce noise at all"]}'::jsonb
  WHERE id = 'r-mcq-15' AND task_type = 'reading-mcq-single' AND payload::text ~ '[\u4e00-\u9fff]';
UPDATE pte_practice_items SET payload = payload || '{"question":"Why have nutrition guidelines shifted to emphasise overall eating patterns?","options":["Individual foods no longer matter at all","Focusing too much on single nutrients or foods can lead to compensating behaviour that cancels out the benefits","It makes marketing easier for food companies","Overall patterns are cheaper than individual foods"]}'::jsonb
  WHERE id = 'r-mcq-16' AND task_type = 'reading-mcq-single' AND payload::text ~ '[\u4e00-\u9fff]';
UPDATE pte_practice_items SET payload = payload || '{"question":"What reservation do critics have about the \"comprehensible input\" theory?","options":["Children need no language input at all","Adult learners may still need some explicit grammar instruction","The theory has been completely disproven","Grammar practice is useless for everyone"]}'::jsonb
  WHERE id = 'r-mcq-17' AND task_type = 'reading-mcq-single' AND payload::text ~ '[\u4e00-\u9fff]';
UPDATE pte_practice_items SET payload = payload || '{"question":"According to the passage, what are the reasons for installing more public drinking fountains? Select all that apply.","options":["Less plastic bottle waste","Free access to water for low-income residents","Fewer dehydration-related emergency visits during heat waves","No maintenance costs at all"]}'::jsonb
  WHERE id = 'r-mcqm-1' AND task_type = 'reading-mcq-multiple' AND payload::text ~ '[\u4e00-\u9fff]';
UPDATE pte_practice_items SET payload = payload || '{"question":"According to the passage, what are the arguments for a four-day work week? Select all that apply.","options":["Reduced burnout","Lower commuting-related emissions","Maintained or improved productivity in several pilot studies","Suitable for every industry without exception"]}'::jsonb
  WHERE id = 'r-mcqm-2' AND task_type = 'reading-mcq-multiple' AND payload::text ~ '[\u4e00-\u9fff]';
UPDATE pte_practice_items SET payload = payload || '{"question":"According to the passage, what are the benefits of community gardens? Select all that apply.","options":["Better access to fresh produce","Opportunities for neighbours to interact","Modest reductions in local food-transport emissions","No need for volunteers to maintain them"]}'::jsonb
  WHERE id = 'r-mcqm-3' AND task_type = 'reading-mcq-multiple' AND payload::text ~ '[\u4e00-\u9fff]';
UPDATE pte_practice_items SET payload = payload || '{"question":"According to the passage, what are the advantages of digital note-taking apps? Select all that apply.","options":["Searchable text","Easy sharing","Automatic backups","Proven to support memory better than handwriting"]}'::jsonb
  WHERE id = 'r-mcqm-4' AND task_type = 'reading-mcq-multiple' AND payload::text ~ '[\u4e00-\u9fff]';
UPDATE pte_practice_items SET payload = payload || '{"question":"According to the passage, what are the arguments for congestion pricing? Select all that apply.","options":["Less traffic congestion","Lower air pollution","Revenue that can be used to improve public transport","Exactly the same impact on all income groups"]}'::jsonb
  WHERE id = 'r-mcqm-5' AND task_type = 'reading-mcq-multiple' AND payload::text ~ '[\u4e00-\u9fff]';
UPDATE pte_practice_items SET payload = payload || '{"question":"According to the passage, what problems do open-plan offices have? Select all that apply.","options":["Higher noise levels","Less face-to-face interaction","Lower construction costs","No effect on how employees communicate"]}'::jsonb
  WHERE id = 'r-mcqm-6' AND task_type = 'reading-mcq-multiple' AND payload::text ~ '[\u4e00-\u9fff]';
UPDATE pte_practice_items SET payload = payload || '{"question":"According to the passage, what benefits do supporters of urban composting programs mention? Select all that apply.","options":["Less methane from landfills","Nutrient-rich soil for community gardens","Lower municipal waste collection costs","No unpleasant odours at all"]}'::jsonb
  WHERE id = 'r-mcqm-7' AND task_type = 'reading-mcq-multiple' AND payload::text ~ '[\u4e00-\u9fff]';
UPDATE pte_practice_items SET payload = payload || '{"question":"According to the passage, what cognitive advantages have researchers found in bilingual children? Select all that apply.","options":["Better task-switching ability","Better at ignoring irrelevant information","Significantly higher overall intelligence than monolingual children","These advantages are modest and do not reflect higher overall intelligence"]}'::jsonb
  WHERE id = 'r-mcqm-8' AND task_type = 'reading-mcq-multiple' AND payload::text ~ '[\u4e00-\u9fff]';
UPDATE pte_practice_items SET payload = payload || '{"question":"According to the passage, what arguments do supporters of carbon capture make? Select all that apply.","options":["It lets existing power plants keep running while cutting emissions","It creates new industries around underground storage","It is currently cheap to use at large scale","It has no effect at all on investment in renewable energy"]}'::jsonb
  WHERE id = 'r-mcqm-9' AND task_type = 'reading-mcq-multiple' AND payload::text ~ '[\u4e00-\u9fff]';
UPDATE pte_practice_items SET payload = payload || '{"question":"According to the passage, what arguments do supporters of school uniforms make? Select all that apply.","options":["They reduce visible economic differences between students","They simplify families'' morning routines","Some surveys show a modest reduction in clothing-related bullying","They have been proven to significantly improve academic results"]}'::jsonb
  WHERE id = 'r-mcqm-10' AND task_type = 'reading-mcq-multiple' AND payload::text ~ '[\u4e00-\u9fff]';
UPDATE pte_practice_items SET payload = payload || '{"question":"According to the passage, what benefits do wildlife corridors bring? Select all that apply.","options":["Greater genetic diversity in isolated populations","Fewer animals killed on roads because they are guided away from traffic","Almost no construction cost","No need to negotiate with any landowners"]}'::jsonb
  WHERE id = 'r-mcqm-11' AND task_type = 'reading-mcq-multiple' AND payload::text ~ '[\u4e00-\u9fff]';
UPDATE pte_practice_items SET payload = payload || '{"question":"According to the passage, what advantages do supporters of open-source software mention? Select all that apply.","options":["Greater transparency","Faster discovery of security flaws through community review","Freedom from lock-in to a single vendor","Maintenance and support that are always more reliable than commercial software"]}'::jsonb
  WHERE id = 'r-mcqm-12' AND task_type = 'reading-mcq-multiple' AND payload::text ~ '[\u4e00-\u9fff]';
UPDATE pte_practice_items SET payload = payload || '{"question":"According to the passage, what changes did regular users of meditation apps report? Select all that apply.","options":["Improvements in self-reported stress","Better sleep quality","More daily mindfulness practice","A complete replacement for clinical treatment of anxiety disorders"]}'::jsonb
  WHERE id = 'r-mcqm-13' AND task_type = 'reading-mcq-multiple' AND payload::text ~ '[\u4e00-\u9fff]';
UPDATE pte_practice_items SET payload = payload || '{"question":"According to the passage, what concerns do opponents of nuclear power raise? Select all that apply.","options":["Long-term storage of radioactive waste","High upfront capital costs of new plants","Very high operational carbon emissions","Inability to provide stable baseload power"]}'::jsonb
  WHERE id = 'r-mcqm-14' AND task_type = 'reading-mcq-multiple' AND payload::text ~ '[\u4e00-\u9fff]';
UPDATE pte_practice_items SET payload = payload || '{"question":"According to the passage, what arguments do supporters of telehealth make? Select all that apply.","options":["Better access to care for patients in rural areas","Less travel time and cost for patients","Remote monitoring of chronic conditions between visits","A complete replacement for all diagnoses that require a physical examination"]}'::jsonb
  WHERE id = 'r-mcqm-15' AND task_type = 'reading-mcq-multiple' AND payload::text ~ '[\u4e00-\u9fff]';
UPDATE pte_practice_items SET payload = payload || '{"question":"Which of the following best summarizes the recording?","options":["City governments are turning unused parking lots into small parks, a move welcomed by some residents but raising concerns among businesses about lost parking","All businesses strongly oppose any kind of urban greening project","The government has cancelled the parking lot conversion project entirely","The recording mainly discusses how to raise parking fees"]}'::jsonb
  WHERE id = 'l-summary-1' AND task_type = 'listening-highlight-summary' AND payload::text ~ '[\u4e00-\u9fff]';
UPDATE pte_practice_items SET payload = payload || '{"question":"Which of the following best summarizes the recording?","options":["Skin changes in sleeping octopuses suggest a possible dream-like state, although scientists remain cautious","Scientists have proven that octopuses dream exactly as humans do","Octopuses never change skin colour while asleep","The study has nothing to do with octopus sleep"]}'::jsonb
  WHERE id = 'l-summary-2' AND task_type = 'listening-highlight-summary' AND payload::text ~ '[\u4e00-\u9fff]';
UPDATE pte_practice_items SET payload = payload || '{"question":"Which of the following best summarizes the recording?","options":["Dedicated bike lanes increase cyclist satisfaction and reduce stress, leading several cities to expand cycling budgets","Cycling to work significantly increases riders'' stress","The study found that cities do not need bike lanes at all","The study is mainly about the satisfaction of car drivers"]}'::jsonb
  WHERE id = 'l-summary-3' AND task_type = 'listening-highlight-summary' AND payload::text ~ '[\u4e00-\u9fff]';
UPDATE pte_practice_items SET payload = payload || '{"question":"Which of the following best summarizes the recording?","options":["New tree-ring and sediment analysis suggests that prolonged drought and political unrest together caused the decline of the ancient trading city","Historians have completely ruled out climate as a factor","War was the only cause of the city''s decline","The recording mainly discusses how to rebuild the ancient city"]}'::jsonb
  WHERE id = 'l-summary-4' AND task_type = 'listening-highlight-summary' AND payload::text ~ '[\u4e00-\u9fff]';
UPDATE pte_practice_items SET payload = payload || '{"question":"Which of the following best summarizes the recording?","options":["The experiment found that people who focused on one task completed more work with fewer errors than multitaskers","Multitasking has been proven to always be more efficient","The recording has nothing to do with productivity","The results are unusable because the sample was too small"]}'::jsonb
  WHERE id = 'l-summary-5' AND task_type = 'listening-highlight-summary' AND payload::text ~ '[\u4e00-\u9fff]';
UPDATE pte_practice_items SET payload = payload || '{"question":"Which of the following best summarizes the recording?","options":["The study found markedly higher rates of metabolic disorders among night-shift workers, which researchers link to disrupted circadian rhythms","Diet is the only cause of metabolic disorders in night-shift workers","There is no difference in health between day-shift and night-shift workers","The study is mainly about the pay of night-shift workers"]}'::jsonb
  WHERE id = 'l-summary-6' AND task_type = 'listening-highlight-summary' AND payload::text ~ '[\u4e00-\u9fff]';
UPDATE pte_practice_items SET payload = payload || '{"question":"Which of the following best summarizes the recording?","options":["Digitised city archives make it easier for amateur historians to trace family history, but handwritten records are still hard for recognition software to read accurately","All historical archives can now be read automatically and no longer need manual checking","The digitisation project has stopped completely with no progress","The recording mainly discusses how to repair damaged paper documents"]}'::jsonb
  WHERE id = 'l-summary-7' AND task_type = 'listening-highlight-summary' AND payload::text ~ '[\u4e00-\u9fff]';
UPDATE pte_practice_items SET payload = payload || '{"question":"Which of the following best summarizes the recording?","options":["Small business owners using cloud accounting software save bookkeeping time each week, but many report a steep learning curve at first and need outside help","Cloud accounting software is of no help to small businesses","All small business owners mastered cloud accounting software easily without any difficulty","The recording mainly discusses tax issues for small businesses"]}'::jsonb
  WHERE id = 'l-summary-8' AND task_type = 'listening-highlight-summary' AND payload::text ~ '[\u4e00-\u9fff]';
UPDATE pte_practice_items SET payload = payload || '{"question":"Which of the following best summarizes the recording?","options":["Reintroducing beavers has brought benefits such as more wetland habitat and less downstream flooding, although a few landowners reported local damage","Reintroducing beavers has had no ecological impact at all","All landowners strongly oppose the beaver reintroduction plan","The recording mainly discusses how to hunt beavers"]}'::jsonb
  WHERE id = 'l-summary-9' AND task_type = 'listening-highlight-summary' AND payload::text ~ '[\u4e00-\u9fff]';
UPDATE pte_practice_items SET payload = payload || '{"question":"Which of the following best summarizes the recording?","options":["Human translators still outperform machine translation on texts requiring cultural nuance or humour, while machine translation now performs comparably on technical documents","Machine translation has completely surpassed human translation for all types of text","Human translation has been completely phased out","The recording mainly discusses salaries in the translation industry"]}'::jsonb
  WHERE id = 'l-summary-10' AND task_type = 'listening-highlight-summary' AND payload::text ~ '[\u4e00-\u9fff]';
UPDATE pte_practice_items SET payload = payload || '{"question":"Which of the following best summarizes the recording?","options":["Students seated in a semicircle participated more in class, but there was no significant difference in exam results between the two groups","Seating arrangements have no effect on either participation or exam results","Students seated in traditional rows participated significantly more","The recording mainly discusses how to design classroom lighting"]}'::jsonb
  WHERE id = 'l-summary-11' AND task_type = 'listening-highlight-summary' AND payload::text ~ '[\u4e00-\u9fff]';
UPDATE pte_practice_items SET payload = payload || '{"question":"Which of the following best summarizes the recording?","options":["Simple measures such as sealing drafts and adding insulation usually pay for themselves faster than replacing heating systems, even though the latter gets more attention in advertising","Replacing the heating system is always the most cost-effective option","Home energy audits have no effect on payback time","The recording mainly discusses how to choose a heating system brand"]}'::jsonb
  WHERE id = 'l-summary-12' AND task_type = 'listening-highlight-summary' AND payload::text ~ '[\u4e00-\u9fff]';
UPDATE pte_practice_items SET payload = payload || '{"question":"Which of the following best summarizes the recording?","options":["Shorter night shifts for junior doctors, with the same total hours, are linked to fewer medical errors, prompting several hospitals to redesign their rosters","Longer night shifts significantly reduce medical errors","Hospital rosters have nothing to do with medical errors","The recording mainly discusses doctors'' pay structure"]}'::jsonb
  WHERE id = 'l-summary-13' AND task_type = 'listening-highlight-summary' AND payload::text ~ '[\u4e00-\u9fff]';
UPDATE pte_practice_items SET payload = payload || '{"question":"Which of the following best summarizes the recording?","options":["Community-led projects that train local speakers to record their own language tend to be richer and more culturally grounded than projects run entirely by outside academics","Projects run by outside academics are always of higher quality","Documenting endangered languages is no longer necessary","The recording mainly discusses how to apply for government funding for endangered languages"]}'::jsonb
  WHERE id = 'l-summary-14' AND task_type = 'listening-highlight-summary' AND payload::text ~ '[\u4e00-\u9fff]';
UPDATE pte_practice_items SET payload = payload || '{"question":"Which of the following best summarizes the recording?","options":["Dockless bike-share systems are used more, but bikes are more often left in inconvenient or unsafe places","Docked bike-share systems are always used more","Bike-share programs have been shown to have no demand at all","The recording mainly discusses bike-share pricing strategies"]}'::jsonb
  WHERE id = 'l-summary-15' AND task_type = 'listening-highlight-summary' AND payload::text ~ '[\u4e00-\u9fff]';
UPDATE pte_practice_items SET payload = payload || '{"question":"According to the lecture, why does honey not spoil?","options":["Because it has a low sugar content","Because its low moisture content and acidity prevent bacteria from surviving","Because it is always stored in sealed containers","Because bees add preservatives to it"]}'::jsonb
  WHERE id = 'l-mcqs-1' AND task_type = 'listening-mcq-single' AND payload::text ~ '[\u4e00-\u9fff]';
UPDATE pte_practice_items SET payload = payload || '{"question":"According to the lecture, why does the sky look blue?","options":["Because the atmosphere contains a blue gas","Because blue light has a shorter wavelength and is scattered more easily by the atmosphere","Because the sun emits only blue light","Because the human eye can only see blue light"]}'::jsonb
  WHERE id = 'l-mcqs-2' AND task_type = 'listening-mcq-single' AND payload::text ~ '[\u4e00-\u9fff]';
UPDATE pte_practice_items SET payload = payload || '{"question":"According to the lecture, what is contagious yawning associated with?","options":["The temperature of the room","Empathy, as it is more common between people who are emotionally close","The age of the person yawning","The time of day"]}'::jsonb
  WHERE id = 'l-mcqs-3' AND task_type = 'listening-mcq-single' AND payload::text ~ '[\u4e00-\u9fff]';
UPDATE pte_practice_items SET payload = payload || '{"question":"According to the lecture, why does cutting onions make people cry?","options":["A gas released by the onion reacts with moisture in the eyes to form an irritant","Onions contain capsaicin","It is only a psychological effect","The smell of onions is too strong"]}'::jsonb
  WHERE id = 'l-mcqs-4' AND task_type = 'listening-mcq-single' AND payload::text ~ '[\u4e00-\u9fff]';
UPDATE pte_practice_items SET payload = payload || '{"question":"According to the lecture, why does bamboo grow so quickly?","options":["It constantly produces new cells","Its stem segments are already formed at the base and lengthen quickly as existing cells expand","It needs almost no sunlight","Its roots are especially shallow"]}'::jsonb
  WHERE id = 'l-mcqs-5' AND task_type = 'listening-mcq-single' AND payload::text ~ '[\u4e00-\u9fff]';
UPDATE pte_practice_items SET payload = payload || '{"question":"According to the lecture, why do aircraft windows have rounded corners?","options":["Rounded windows are cheaper","Rounded corners spread stress on the fuselage more evenly instead of concentrating it at sharp corners","Rounded windows give a better view","It is simply an aesthetic design choice"]}'::jsonb
  WHERE id = 'l-mcqs-6' AND task_type = 'listening-mcq-single' AND payload::text ~ '[\u4e00-\u9fff]';
UPDATE pte_practice_items SET payload = payload || '{"question":"According to the lecture, why do humans get goosebumps?","options":["It is a completely new evolutionary adaptation","It is a reflex inherited from our ancestors that raised body hair for warmth, but modern humans have too little hair for it to work","It is purely psychological and unrelated to the body","It only happens in extremely cold weather"]}'::jsonb
  WHERE id = 'l-mcqs-7' AND task_type = 'listening-mcq-single' AND payload::text ~ '[\u4e00-\u9fff]';
UPDATE pte_practice_items SET payload = payload || '{"question":"According to the lecture, what is the main reason bread goes stale?","options":["All of its moisture evaporates","Starch molecules gradually recrystallise into a harder structure","Refrigeration effectively stops bread from going stale","Bread only goes stale in summer"]}'::jsonb
  WHERE id = 'l-mcqs-8' AND task_type = 'listening-mcq-single' AND payload::text ~ '[\u4e00-\u9fff]';
UPDATE pte_practice_items SET payload = payload || '{"question":"According to the lecture, why were coins originally given ridged edges?","options":["To make coins easier to stack","To stop people from secretly shaving metal off the edges of precious-metal coins","To make coins look more attractive","To make coins easier to produce"]}'::jsonb
  WHERE id = 'l-mcqs-9' AND task_type = 'listening-mcq-single' AND payload::text ~ '[\u4e00-\u9fff]';
UPDATE pte_practice_items SET payload = payload || '{"question":"According to the lecture, why do spiders rebuild their webs every night?","options":["The old web can no longer be repaired","Fresh silk is stickier and more effective, and rebuilding lets the spider recycle protein from the old web","It is a purely instinctive behaviour with no practical function","Rebuilding takes less time than repairing the old web"]}'::jsonb
  WHERE id = 'l-mcqs-10' AND task_type = 'listening-mcq-single' AND payload::text ~ '[\u4e00-\u9fff]';
UPDATE pte_practice_items SET payload = payload || '{"question":"According to the lecture, why does your voice sound higher after inhaling helium?","options":["Helium changes the way the vocal cords vibrate","Sound travels faster in helium, raising the resonant frequencies of the vocal tract while the vocal cords stay the same","Helium temporarily paralyses the vocal cords","It is only a psychological illusion"]}'::jsonb
  WHERE id = 'l-mcqs-11' AND task_type = 'listening-mcq-single' AND payload::text ~ '[\u4e00-\u9fff]';
UPDATE pte_practice_items SET payload = payload || '{"question":"According to the lecture, what is the historical origin of driving on the left?","options":["It was introduced by modern traffic laws","Horse riders kept their right hand, their sword hand, free to deal with oncoming riders","It relates to the design of carriages rather than riders","The tradition has no historical basis"]}'::jsonb
  WHERE id = 'l-mcqs-12' AND task_type = 'listening-mcq-single' AND payload::text ~ '[\u4e00-\u9fff]';
UPDATE pte_practice_items SET payload = payload || '{"question":"According to the lecture, where does kneading behaviour in cats come from?","options":["It is an aggressive behaviour","It comes from kittens stimulating their mother''s milk flow and is kept into adulthood as a sign of comfort","It is how cats mark their territory","It only happens in injured cats"]}'::jsonb
  WHERE id = 'l-mcqs-13' AND task_type = 'listening-mcq-single' AND payload::text ~ '[\u4e00-\u9fff]';
UPDATE pte_practice_items SET payload = payload || '{"question":"According to the lecture, why do old photographs have a sepia tone?","options":["Cameras at the time could only capture brown tones","A chemical toning process used to make the silver in the image more stable also produced the sepia colour","Photographers deliberately chose it as an artistic effect","It is the result of photographs fading naturally over time"]}'::jsonb
  WHERE id = 'l-mcqs-14' AND task_type = 'listening-mcq-single' AND payload::text ~ '[\u4e00-\u9fff]';
UPDATE pte_practice_items SET payload = payload || '{"question":"According to the lecture, how does a leading neurological theory explain déjà vu?","options":["It is evidence of supernatural phenomena","The brain''s memory circuits briefly misfire and wrongly tag a new experience as a familiar memory","It only happens to people who lack sleep","It is caused by a physical defect in the eyes"]}'::jsonb
  WHERE id = 'l-mcqs-15' AND task_type = 'listening-mcq-single' AND payload::text ~ '[\u4e00-\u9fff]';
UPDATE pte_practice_items SET payload = payload || '{"question":"According to the lecture, what benefits do urban trees bring? Select all that apply.","options":["Lower street temperatures in summer","Less stormwater runoff","Reduced traffic noise","Complete elimination of air pollution"]}'::jsonb
  WHERE id = 'l-mcqm-1' AND task_type = 'listening-mcq-multiple' AND payload::text ~ '[\u4e00-\u9fff]';
UPDATE pte_practice_items SET payload = payload || '{"question":"According to the lecture, what changes did employees with more natural light report? Select all that apply.","options":["Better sleep","Fewer headaches","Slightly higher self-rated productivity","Significantly better eyesight"]}'::jsonb
  WHERE id = 'l-mcqm-2' AND task_type = 'listening-mcq-multiple' AND payload::text ~ '[\u4e00-\u9fff]';
UPDATE pte_practice_items SET payload = payload || '{"question":"According to the lecture, what might whales rely on to navigate during migration? Select all that apply.","options":["Ocean currents","Water temperature gradients","The Earth''s magnetic field","Sounds made by ships"]}'::jsonb
  WHERE id = 'l-mcqm-3' AND task_type = 'listening-mcq-multiple' AND payload::text ~ '[\u4e00-\u9fff]';
UPDATE pte_practice_items SET payload = payload || '{"question":"According to the lecture, what challenges do remote workers face? Select all that apply.","options":["Blurred boundaries between work and home life","A sense of isolation from colleagues","A lack of suitable home office equipment","Long commutes"]}'::jsonb
  WHERE id = 'l-mcqm-4' AND task_type = 'listening-mcq-multiple' AND payload::text ~ '[\u4e00-\u9fff]';
UPDATE pte_practice_items SET payload = payload || '{"question":"According to the lecture, what benefits might fermented foods offer? Select all that apply.","options":["Introducing beneficial bacteria","Making some nutrients easier to digest","A link to modest improvements in mood","Completely replacing all medication"]}'::jsonb
  WHERE id = 'l-mcqm-5' AND task_type = 'listening-mcq-multiple' AND payload::text ~ '[\u4e00-\u9fff]';
UPDATE pte_practice_items SET payload = payload || '{"question":"According to the lecture, what did the research find about libraries? Select all that apply.","options":["Users of quiet study rooms reported better concentration","Physical book loans have stayed stable despite e-books","Children''s community events brought in many visitors","Children''s events have been cancelled at every library"]}'::jsonb
  WHERE id = 'l-mcqm-6' AND task_type = 'listening-mcq-multiple' AND payload::text ~ '[\u4e00-\u9fff]';
UPDATE pte_practice_items SET payload = payload || '{"question":"According to the lecture, what patterns did the research find in online learning? Select all that apply.","options":["Students who set specific weekly goals were more likely to finish the course","Video lectures under ten minutes had higher completion rates","Peer discussion forums modestly improved knowledge retention","Video length has no relationship with completion rates"]}'::jsonb
  WHERE id = 'l-mcqm-7' AND task_type = 'listening-mcq-multiple' AND payload::text ~ '[\u4e00-\u9fff]';
UPDATE pte_practice_items SET payload = payload || '{"question":"According to the lecture, what results has urban farming produced? Select all that apply.","options":["Lower building cooling costs in summer","A stronger sense of local identity among residents","Small harvests that often sell at higher prices because they are fresh","Harvests that already exceed those of traditional rural farms"]}'::jsonb
  WHERE id = 'l-mcqm-8' AND task_type = 'listening-mcq-multiple' AND payload::text ~ '[\u4e00-\u9fff]';
UPDATE pte_practice_items SET payload = payload || '{"question":"According to the lecture, what did the survey of long-distance runners find? Select all that apply.","options":["Runners who tapered their training before races performed better","Hydration strategies varied widely between runners","Pre-race anxiety was not strongly linked to final results","All runners used exactly the same hydration strategy"]}'::jsonb
  WHERE id = 'l-mcqm-9' AND task_type = 'listening-mcq-multiple' AND payload::text ~ '[\u4e00-\u9fff]';
UPDATE pte_practice_items SET payload = payload || '{"question":"According to the lecture, what did the call centre study find? Select all that apply.","options":["Shorter hold-music loops reduced caller frustration","Agents with more autonomy reported higher job satisfaction","Call volume peaks predictably at the start of each working day","Call volume stays perfectly even throughout the day"]}'::jsonb
  WHERE id = 'l-mcqm-10' AND task_type = 'listening-mcq-multiple' AND payload::text ~ '[\u4e00-\u9fff]';
UPDATE pte_practice_items SET payload = payload || '{"question":"According to the lecture, what did the research on carnivorous plants find? Select all that apply.","options":["Most species evolved in nutrient-poor soils","Their trapping mechanisms are highly specialised for particular prey","The time needed to digest trapped insects varies by species","All carnivorous plants digest at exactly the same speed"]}'::jsonb
  WHERE id = 'l-mcqm-11' AND task_type = 'listening-mcq-multiple' AND payload::text ~ '[\u4e00-\u9fff]';
UPDATE pte_practice_items SET payload = payload || '{"question":"According to the lecture, what did the analysis of household energy use find? Select all that apply.","options":["Appliances on standby make up a considerable share of monthly electricity bills","Smart thermostats modestly reduced heating costs","Time-of-use pricing led some households to move laundry to off-peak hours","Appliances on standby have no effect on electricity bills"]}'::jsonb
  WHERE id = 'l-mcqm-12' AND task_type = 'listening-mcq-multiple' AND payload::text ~ '[\u4e00-\u9fff]';
UPDATE pte_practice_items SET payload = payload || '{"question":"According to the lecture, what did the study of professional orchestras find? Select all that apply.","options":["Blind auditions increased the proportion of women advancing to later rounds","Seating arrangements affect how musicians perceive the overall tempo","Rehearsal frequency is linked to consistent performances","Blind auditions had no effect on advancement rates"]}'::jsonb
  WHERE id = 'l-mcqm-13' AND task_type = 'listening-mcq-multiple' AND payload::text ~ '[\u4e00-\u9fff]';
UPDATE pte_practice_items SET payload = payload || '{"question":"According to the lecture, what did the study of traffic accident data find? Select all that apply.","options":["Intersections with dedicated left-turn signals had fewer collisions","Lower speed limits near schools were linked to fewer pedestrian injuries","Crashes at roundabouts were usually less severe than at traditional four-way intersections","Speed limits have no effect on pedestrian safety"]}'::jsonb
  WHERE id = 'l-mcqm-14' AND task_type = 'listening-mcq-multiple' AND payload::text ~ '[\u4e00-\u9fff]';
UPDATE pte_practice_items SET payload = payload || '{"question":"According to the lecture, what did the review of workplace mentoring programs find? Select all that apply.","options":["Mentees developed skills faster","Mentors often felt more engaged with their own work","Programs with structured, regular check-ins were more effective than informal, occasional pairings","Informal pairings were always more effective than structured programs"]}'::jsonb
  WHERE id = 'l-mcqm-15' AND task_type = 'listening-mcq-multiple' AND payload::text ~ '[\u4e00-\u9fff]';
UPDATE pte_practice_items SET payload = payload || '{"chart":{"type":"bar","title":"Commuting by transport mode in a city","categories":["Walking","Cycling","Bus","Car"],"values":[15,20,35,30],"unit":"%"}}'::jsonb
  WHERE id = 's-di-1' AND task_type = 'speaking-describe-image' AND payload::text ~ '[\u4e00-\u9fff]';
UPDATE pte_practice_items SET payload = payload || '{"chart":{"type":"line","title":"Product sales over five years (10,000 units)","categories":["2021","2022","2023","2024","2025"],"values":[12,18,22,30,45]}}'::jsonb
  WHERE id = 's-di-2' AND task_type = 'speaking-describe-image' AND payload::text ~ '[\u4e00-\u9fff]';
UPDATE pte_practice_items SET payload = payload || '{"chart":{"type":"bar","title":"University students'' weekly extracurricular time (hours)","categories":["Sports","Clubs","Part-time work","Leisure"],"values":[4,3,6,8],"unit":"h"}}'::jsonb
  WHERE id = 's-di-3' AND task_type = 'speaking-describe-image' AND payload::text ~ '[\u4e00-\u9fff]';
UPDATE pte_practice_items SET payload = payload || '{"chart":{"type":"line","title":"Average annual temperature in a region (°C)","categories":["2000","2010","2020","2024"],"values":[14,14.5,15.3,16]}}'::jsonb
  WHERE id = 's-di-4' AND task_type = 'speaking-describe-image' AND payload::text ~ '[\u4e00-\u9fff]';
UPDATE pte_practice_items SET payload = payload || '{"chart":{"type":"bar","title":"Quarterly revenue of a company (USD millions)","categories":["Q1","Q2","Q3","Q4"],"values":[8,11,9,15],"unit":"M"}}'::jsonb
  WHERE id = 's-di-5' AND task_type = 'speaking-describe-image' AND payload::text ~ '[\u4e00-\u9fff]';
UPDATE pte_practice_items SET payload = payload || '{"chart":{"type":"line","title":"Internet penetration in a country (%)","categories":["2005","2010","2015","2020","2025"],"values":[10,28,50,72,88],"unit":"%"}}'::jsonb
  WHERE id = 's-di-6' AND task_type = 'speaking-describe-image' AND payload::text ~ '[\u4e00-\u9fff]';
UPDATE pte_practice_items SET payload = payload || '{"chart":{"type":"bar","title":"Weekly reading time by age group (hours)","categories":["18-25","26-40","41-60","60+"],"values":[3,4,6,9],"unit":"h"}}'::jsonb
  WHERE id = 's-di-7' AND task_type = 'speaking-describe-image' AND payload::text ~ '[\u4e00-\u9fff]';
UPDATE pte_practice_items SET payload = payload || '{"chart":{"type":"line","title":"Water level of a lake (metres)","categories":["2000","2008","2016","2024"],"values":[12.5,11.8,10.2,8.6],"unit":"m"}}'::jsonb
  WHERE id = 's-di-8' AND task_type = 'speaking-describe-image' AND payload::text ~ '[\u4e00-\u9fff]';
UPDATE pte_practice_items SET payload = payload || '{"chart":{"type":"bar","title":"Household energy use by source","categories":["Heating","Hot water","Appliances","Lighting"],"values":[40,25,25,10],"unit":"%"}}'::jsonb
  WHERE id = 's-di-9' AND task_type = 'speaking-describe-image' AND payload::text ~ '[\u4e00-\u9fff]';
UPDATE pte_practice_items SET payload = payload || '{"chart":{"type":"line","title":"Global market share of a smartphone brand (%)","categories":["2019","2021","2023","2025"],"values":[18,15,12,9],"unit":"%"}}'::jsonb
  WHERE id = 's-di-10' AND task_type = 'speaking-describe-image' AND payload::text ~ '[\u4e00-\u9fff]';
UPDATE pte_practice_items SET payload = payload || '{"chart":{"type":"bar","title":"Average annual commuting carbon emissions by transport mode (kg)","categories":["Walking","Bus","Car","Plane"],"values":[0,120,800,2000],"unit":"kg"}}'::jsonb
  WHERE id = 's-di-11' AND task_type = 'speaking-describe-image' AND payload::text ~ '[\u4e00-\u9fff]';
UPDATE pte_practice_items SET payload = payload || '{"chart":{"type":"line","title":"Annual outpatient visits at a hospital (10,000 visits)","categories":["2018","2020","2022","2024"],"values":[45,38,52,61],"unit":""}}'::jsonb
  WHERE id = 's-di-12' AND task_type = 'speaking-describe-image' AND payload::text ~ '[\u4e00-\u9fff]';
UPDATE pte_practice_items SET payload = payload || '{"chart":{"type":"bar","title":"Choice of major among first-year university students","categories":["Engineering","Business","Humanities","Medicine"],"values":[30,28,18,24],"unit":"%"}}'::jsonb
  WHERE id = 's-di-13' AND task_type = 'speaking-describe-image' AND payload::text ~ '[\u4e00-\u9fff]';
UPDATE pte_practice_items SET payload = payload || '{"chart":{"type":"line","title":"Forest cover in a region (%)","categories":["1990","2000","2010","2020"],"values":[65,58,50,47],"unit":"%"}}'::jsonb
  WHERE id = 's-di-14' AND task_type = 'speaking-describe-image' AND payload::text ~ '[\u4e00-\u9fff]';
UPDATE pte_practice_items SET payload = payload || '{"chart":{"type":"bar","title":"Daily smartphone use by age group (hours)","categories":["13-18","19-30","31-50","50+"],"values":[5,4.5,3,1.5],"unit":"h"}}'::jsonb
  WHERE id = 's-di-15' AND task_type = 'speaking-describe-image' AND payload::text ~ '[\u4e00-\u9fff]';
UPDATE pte_practice_items SET payload = payload || '{"prompt":"Read the passage below and summarize it in one sentence of no more than 75 words."}'::jsonb
  WHERE id = 'w-swt-1' AND task_type = 'writing-summarize-text' AND payload::text ~ '[\u4e00-\u9fff]';
UPDATE pte_practice_items SET payload = payload || '{"prompt":"Read the passage below and summarize it in one sentence of no more than 75 words."}'::jsonb
  WHERE id = 'w-swt-2' AND task_type = 'writing-summarize-text' AND payload::text ~ '[\u4e00-\u9fff]';
UPDATE pte_practice_items SET payload = payload || '{"prompt":"Read the passage below and summarize it in one sentence of no more than 75 words."}'::jsonb
  WHERE id = 'w-swt-3' AND task_type = 'writing-summarize-text' AND payload::text ~ '[\u4e00-\u9fff]';
UPDATE pte_practice_items SET payload = payload || '{"prompt":"Read the passage below and summarize it in one sentence of no more than 75 words."}'::jsonb
  WHERE id = 'w-swt-4' AND task_type = 'writing-summarize-text' AND payload::text ~ '[\u4e00-\u9fff]';
UPDATE pte_practice_items SET payload = payload || '{"prompt":"Read the passage below and summarize it in one sentence of no more than 75 words."}'::jsonb
  WHERE id = 'w-swt-5' AND task_type = 'writing-summarize-text' AND payload::text ~ '[\u4e00-\u9fff]';
UPDATE pte_practice_items SET payload = payload || '{"prompt":"Read the passage below and summarize it in one sentence of no more than 75 words."}'::jsonb
  WHERE id = 'w-swt-6' AND task_type = 'writing-summarize-text' AND payload::text ~ '[\u4e00-\u9fff]';
UPDATE pte_practice_items SET payload = payload || '{"prompt":"Read the passage below and summarize it in one sentence of no more than 75 words."}'::jsonb
  WHERE id = 'w-swt-7' AND task_type = 'writing-summarize-text' AND payload::text ~ '[\u4e00-\u9fff]';
UPDATE pte_practice_items SET payload = payload || '{"prompt":"Read the passage below and summarize it in one sentence of no more than 75 words."}'::jsonb
  WHERE id = 'w-swt-8' AND task_type = 'writing-summarize-text' AND payload::text ~ '[\u4e00-\u9fff]';
UPDATE pte_practice_items SET payload = payload || '{"prompt":"Read the passage below and summarize it in one sentence of no more than 75 words."}'::jsonb
  WHERE id = 'w-swt-9' AND task_type = 'writing-summarize-text' AND payload::text ~ '[\u4e00-\u9fff]';
UPDATE pte_practice_items SET payload = payload || '{"prompt":"Read the passage below and summarize it in one sentence of no more than 75 words."}'::jsonb
  WHERE id = 'w-swt-10' AND task_type = 'writing-summarize-text' AND payload::text ~ '[\u4e00-\u9fff]';
UPDATE pte_practice_items SET payload = payload || '{"prompt":"Read the passage below and summarize it in one sentence of no more than 75 words."}'::jsonb
  WHERE id = 'w-swt-11' AND task_type = 'writing-summarize-text' AND payload::text ~ '[\u4e00-\u9fff]';
UPDATE pte_practice_items SET payload = payload || '{"prompt":"Read the passage below and summarize it in one sentence of no more than 75 words."}'::jsonb
  WHERE id = 'w-swt-12' AND task_type = 'writing-summarize-text' AND payload::text ~ '[\u4e00-\u9fff]';
UPDATE pte_practice_items SET payload = payload || '{"prompt":"Read the passage below and summarize it in one sentence of no more than 75 words."}'::jsonb
  WHERE id = 'w-swt-13' AND task_type = 'writing-summarize-text' AND payload::text ~ '[\u4e00-\u9fff]';
UPDATE pte_practice_items SET payload = payload || '{"prompt":"Read the passage below and summarize it in one sentence of no more than 75 words."}'::jsonb
  WHERE id = 'w-swt-14' AND task_type = 'writing-summarize-text' AND payload::text ~ '[\u4e00-\u9fff]';
UPDATE pte_practice_items SET payload = payload || '{"prompt":"Read the passage below and summarize it in one sentence of no more than 75 words."}'::jsonb
  WHERE id = 'w-swt-15' AND task_type = 'writing-summarize-text' AND payload::text ~ '[\u4e00-\u9fff]';

COMMIT;
