import type { RespondToSituationItem, SummarizeGroupDiscussionItem } from '../types'

/**
 * 2025 年 8 月 PTE Academic 新增口语题型的原创练习题（非 Pearson 官方真题，非"机经"）。
 * Summarize Group Discussion：三位发言人讨论一个学术话题，参考要点覆盖每位发言人的观点和讨论走向。
 * Respond to a Situation：不超过约 60 词的日常情境，参考要点与参考回答用于估分和作答后对照。
 */

export const speakingSummarizeGroupDiscussion: SummarizeGroupDiscussionItem[] = [
  {
    id: 's-sgd-1',
    taskType: 'speaking-summarize-group-discussion',
    topic: 'Should universities replace live lectures with recorded videos?',
    turns: [
      { speaker: 'Maya', text: 'I think recorded lectures make a lot of sense. Students can pause, rewatch difficult parts, and study at a time that suits them, which really helps those who work part-time or care for family.' },
      { speaker: 'Daniel', text: 'I see the flexibility, but live lectures give you the chance to ask questions straight away. When you watch a video alone, small misunderstandings can grow into bigger gaps before anyone notices.' },
      { speaker: 'Priya', text: 'Both of you have a point. In my experience, attendance drops when everything is online, and students feel less connected to their classmates and lecturers.' },
      { speaker: 'Maya', text: 'That is true, but forcing everyone into a hall at nine in the morning does not guarantee they are paying attention either.' },
      { speaker: 'Daniel', text: 'Maybe the answer is to record the content but keep smaller live sessions for discussion and questions.' },
      { speaker: 'Priya', text: 'I agree. A blended model would keep the flexibility Maya values while protecting the interaction Daniel and I care about.' },
    ],
    keyPoints: [
      'Maya: recorded lectures offer flexibility, students can pause and rewatch, helps students who work or care for family',
      'Daniel: live lectures allow students to ask questions immediately and catch misunderstandings early',
      'Priya: attendance drops online and students feel less connected to classmates and lecturers',
      'The group agrees on a blended model: recorded content plus smaller live discussion sessions',
    ],
    prepSeconds: 10,
  },
  {
    id: 's-sgd-2',
    taskType: 'speaking-summarize-group-discussion',
    topic: 'Is a four-day working week good for companies?',
    turns: [
      { speaker: 'Leo', text: 'The trials I have read about are quite positive. Employees reported less burnout, and many companies kept the same productivity even though people worked one day less.' },
      { speaker: 'Hannah', text: 'Those results come mostly from office jobs, though. Hospitals, shops and factories need staff every day, so a four-day week could simply mean hiring more people and paying more.' },
      { speaker: 'Omar', text: 'I also worry about customers. If a company closes on Fridays, clients may move to competitors who are available all week.' },
      { speaker: 'Leo', text: 'Companies could rotate the day off, so the business stays open while each employee still gets three days of rest.' },
      { speaker: 'Hannah', text: 'Rotation might work for some teams, but it makes scheduling and communication more complicated.' },
      { speaker: 'Omar', text: 'So perhaps it should be tested team by team, with clear targets, rather than introduced across a whole company at once.' },
    ],
    keyPoints: [
      'Leo: trials show less burnout and the same productivity with one day less work',
      'Hannah: results come from office jobs; hospitals, shops and factories need daily staff, raising hiring costs',
      'Omar: closing a day could push customers to competitors',
      'Rotating days off was suggested but makes scheduling and communication harder',
      'Conclusion: test it team by team with clear targets instead of company-wide',
    ],
    prepSeconds: 10,
  },
  {
    id: 's-sgd-3',
    taskType: 'speaking-summarize-group-discussion',
    topic: 'Should cities ban private cars from the city centre?',
    turns: [
      { speaker: 'Sofia', text: 'Banning cars from the centre would make the air cleaner and the streets much safer for walking and cycling. Several European cities have already seen fewer accidents.' },
      { speaker: 'James', text: 'But many small businesses depend on customers who drive in. If people cannot park nearby, they may shop in out-of-town malls instead.' },
      { speaker: 'Mei', text: 'We also need to think about older and disabled residents. Public transport is not always accessible, so a complete ban could leave them isolated.' },
      { speaker: 'Sofia', text: 'Those are fair concerns. Exemptions for disabled drivers and deliveries would be essential.' },
      { speaker: 'James', text: 'And the city would have to improve buses and park-and-ride services before any ban starts, not after.' },
      { speaker: 'Mei', text: 'Then I could support it, as long as it is introduced gradually and the transport improvements come first.' },
    ],
    keyPoints: [
      'Sofia: a ban means cleaner air and safer streets for walking and cycling; fewer accidents in European cities',
      'James: small businesses rely on customers who drive and may lose them to out-of-town malls',
      'Mei: older and disabled residents could be isolated because public transport is not always accessible',
      'Agreed conditions: exemptions for disabled drivers and deliveries, better buses and park-and-ride first',
      'The group could support a gradual ban after transport improvements',
    ],
    prepSeconds: 10,
  },
  {
    id: 's-sgd-4',
    taskType: 'speaking-summarize-group-discussion',
    topic: 'Should students be allowed to use AI tools for assignments?',
    turns: [
      { speaker: 'Ethan', text: 'AI tools are already part of most workplaces, so students should learn to use them properly at university rather than pretend they do not exist.' },
      { speaker: 'Grace', text: 'My concern is that students might skip the thinking process altogether. If a tool writes the essay, the student does not actually develop the skill the assignment is meant to build.' },
      { speaker: 'Ravi', text: 'There is also the problem of fairness. Students who pay for advanced tools may get better results than those who cannot.' },
      { speaker: 'Ethan', text: 'That is why universities should teach clear rules, like using AI for brainstorming or feedback but not for writing the final answer.' },
      { speaker: 'Grace', text: 'And assessments could change too, for example more in-class writing and oral explanations of the work.' },
      { speaker: 'Ravi', text: 'If the university also provides the same tools to everyone, I think a limited and transparent use would be reasonable.' },
    ],
    keyPoints: [
      'Ethan: AI is used in workplaces, so students should learn to use it properly',
      'Grace: students may skip the thinking process and not develop the skills assignments are meant to build',
      'Ravi: fairness problem because some students can pay for better tools',
      'Suggested solutions: clear rules (brainstorming and feedback only), more in-class writing and oral explanations',
      'Conclusion: limited, transparent use is reasonable if the university provides equal access to tools',
    ],
    prepSeconds: 10,
  },
  {
    id: 's-sgd-5',
    taskType: 'speaking-summarize-group-discussion',
    topic: 'Should museums return cultural objects to their countries of origin?',
    turns: [
      { speaker: 'Amara', text: 'Many objects in major museums were taken during colonial times without consent. Returning them is a matter of justice and respect for the communities they came from.' },
      { speaker: 'Thomas', text: 'I agree in principle, but some museums argue they can protect fragile objects better and make them available to millions of international visitors.' },
      { speaker: 'Lin', text: 'That argument feels outdated. Many countries now have excellent museums, and local communities should be able to see their own heritage.' },
      { speaker: 'Thomas', text: 'True. Perhaps each case should be judged individually, looking at how the object was acquired and who can care for it.' },
      { speaker: 'Amara', text: 'Long-term loans and shared research projects could also help both sides keep a relationship.' },
      { speaker: 'Lin', text: 'So we all accept that returns should happen, especially for objects taken by force, with cooperation on how it is done.' },
    ],
    keyPoints: [
      'Amara: many objects were taken in colonial times without consent; returning them is about justice and respect',
      'Thomas: some museums say they protect fragile objects better and reach millions of visitors',
      'Lin: that argument is outdated; many countries have good museums and communities should see their heritage',
      'Suggestions: judge each case individually, use long-term loans and shared research',
      'Conclusion: returns should happen, especially for objects taken by force, through cooperation',
    ],
    prepSeconds: 10,
  },
  {
    id: 's-sgd-6',
    taskType: 'speaking-summarize-group-discussion',
    topic: 'Should homework be abolished in primary schools?',
    turns: [
      { speaker: 'Nadia', text: 'Research suggests homework has very little effect on learning for young children. It often just creates stress for families in the evening.' },
      { speaker: 'Ben', text: 'I am not so sure. Short, regular homework helps children build habits like reading every day and managing their time.' },
      { speaker: 'Clara', text: 'The problem is inequality. Some children have parents who can help them, while others have no quiet place to study at all.' },
      { speaker: 'Nadia', text: 'Exactly, so homework can widen the gap between children rather than close it.' },
      { speaker: 'Ben', text: 'Then maybe homework should be limited to reading for pleasure, which every child can do without much support.' },
      { speaker: 'Clara', text: 'That sounds like a good compromise, and schools could offer homework clubs for anything more demanding.' },
    ],
    keyPoints: [
      'Nadia: homework has little effect on young children’s learning and causes family stress',
      'Ben: short regular homework builds habits such as daily reading and time management',
      'Clara: inequality, since some children get parental help and others have no quiet place to study',
      'Homework may widen the gap between children',
      'Compromise: limit homework to reading for pleasure and offer school homework clubs',
    ],
    prepSeconds: 10,
  },
]

export const speakingRespondToSituation: RespondToSituationItem[] = [
  {
    id: 's-rts-1',
    taskType: 'speaking-respond-to-situation',
    situation: 'You borrowed a laptop from your classmate, Sam, to finish an assignment. While you were using it, the screen suddenly stopped working. Sam needs the laptop tomorrow. Tell Sam what happened and what you plan to do.',
    keyPoints: ['Apologise to Sam', 'Explain that the screen stopped working while you were using it', 'Offer to repair it or pay for the repair', 'Suggest a solution for tomorrow, such as lending your own laptop'],
    sampleResponse: 'Hi Sam, I am really sorry, but something went wrong with your laptop. I was working on my assignment last night and the screen suddenly went black. I have already contacted a repair shop near campus, and I will pay for the repair. Since you need a laptop tomorrow, you are welcome to use mine until yours is fixed. Again, I apologise for the trouble.',
    prepSeconds: 10,
  },
  {
    id: 's-rts-2',
    taskType: 'speaking-respond-to-situation',
    situation: 'You booked a table for six people at a restaurant for your friend’s birthday dinner on Saturday. Two friends have just told you they cannot come. Call the restaurant to change your booking.',
    keyPoints: ['Greet the restaurant and give your name and booking details', 'Explain that two guests cannot come', 'Ask to change the booking from six to four people', 'Thank the staff and confirm the new booking'],
    sampleResponse: 'Hello, my name is Alex and I have a booking for six people this Saturday at seven o’clock for a birthday dinner. Unfortunately, two of my friends can no longer come, so I would like to change the booking to four people, if that is possible. Could you please confirm the change? Thank you very much for your help.',
    prepSeconds: 10,
  },
  {
    id: 's-rts-3',
    taskType: 'speaking-respond-to-situation',
    situation: 'Your neighbour has been playing loud music late at night for several days, and you cannot sleep before an important exam next week. You meet your neighbour in the hallway. Politely explain the problem and ask for help.',
    keyPoints: ['Greet the neighbour politely', 'Explain that the music late at night stops you from sleeping', 'Mention your important exam next week', 'Ask them to lower the volume after a certain time'],
    sampleResponse: 'Hi, sorry to bother you. I wanted to mention something. Over the last few nights I have heard quite loud music quite late, and it has been hard for me to sleep. I have an important exam next week, so rest is really important for me at the moment. Would you mind keeping the volume down after about ten o’clock? I would really appreciate it. Thanks for understanding.',
    prepSeconds: 10,
  },
  {
    id: 's-rts-4',
    taskType: 'speaking-respond-to-situation',
    situation: 'You ordered a jacket online, but the one you received is the wrong size. You need it for a trip in five days. Call the customer service team to explain the problem and ask for a solution.',
    keyPoints: ['Give your order details', 'Explain that you received the wrong size', 'Mention that you need it within five days for a trip', 'Ask for an exchange with fast delivery or a refund'],
    sampleResponse: 'Hello, I am calling about my order number 4521. I ordered a medium jacket, but the one I received is a large. I am going on a trip in five days and I really need the correct size before then. Could you send me a medium with express delivery, please? If that is not possible, I would like a full refund. Thank you.',
    prepSeconds: 10,
  },
  {
    id: 's-rts-5',
    taskType: 'speaking-respond-to-situation',
    situation: 'Your manager has asked you to lead a presentation for a new client tomorrow morning. However, you have a medical appointment at the same time that you booked weeks ago. Speak to your manager about the situation.',
    keyPoints: ['Thank the manager for the opportunity', 'Explain the medical appointment booked weeks ago', 'Suggest alternatives, such as changing the time or preparing slides for a colleague', 'Show willingness to help the presentation succeed'],
    sampleResponse: 'Thank you for asking me to lead the presentation; I would really like to do it. Unfortunately, I have a medical appointment tomorrow morning that I booked several weeks ago and it is difficult to change. Would it be possible to move the presentation to the afternoon? If not, I can prepare the slides and notes tonight and brief a colleague so the presentation still goes well.',
    prepSeconds: 10,
  },
  {
    id: 's-rts-6',
    taskType: 'speaking-respond-to-situation',
    situation: 'You are in a group project at university. One member has not done their part, and the deadline is in three days. The group has asked you to speak to them. Talk to this student about the problem.',
    keyPoints: ['Start in a friendly, non-blaming way', 'Explain that their section is missing and the deadline is in three days', 'Ask whether they are having difficulties', 'Agree on a plan or offer help to finish on time'],
    sampleResponse: 'Hey, have you got a minute? I wanted to check how your part of the project is going. We are planning to put everything together soon because the deadline is in three days, and we have not received your section yet. Is everything okay, or is something making it difficult? If you need help, we could split some of the work, but could you let us know by tomorrow what you can finish?',
    prepSeconds: 10,
  },
  {
    id: 's-rts-7',
    taskType: 'speaking-respond-to-situation',
    situation: 'You are staying at a hotel, and the air conditioning in your room is not working. It is very hot, and you have an early flight tomorrow. Go to the reception desk and ask for help.',
    keyPoints: ['Give your room number', 'Explain that the air conditioning is not working and the room is very hot', 'Mention your early flight and need for sleep', 'Ask for a repair or a different room'],
    sampleResponse: 'Good evening. I am staying in room 312, and unfortunately the air conditioning is not working at all. The room is very hot, and I have an early flight tomorrow morning, so I really need to get some sleep. Could someone repair it tonight, or would it be possible to move me to another room? Thank you for your help.',
    prepSeconds: 10,
  },
  {
    id: 's-rts-8',
    taskType: 'speaking-respond-to-situation',
    situation: 'A new international student has just joined your class and seems unsure where to go for the library and the student services office. You see them looking at a campus map. Offer your help.',
    keyPoints: ['Greet the student and introduce yourself', 'Offer to help with directions', 'Explain where the library and student services are', 'Offer further help or invite them to ask later'],
    sampleResponse: 'Hi, I am Jordan, I think we are in the same class. You look a bit lost; can I help you find anything? The library is the large glass building just behind the main hall, and student services is on the ground floor of the building next to the cafeteria. I am heading that way now, so I can walk with you. Feel free to ask me if you need anything else.',
    prepSeconds: 10,
  },
  {
    id: 's-rts-9',
    taskType: 'speaking-respond-to-situation',
    situation: 'Your friend has invited you to their art exhibition opening this Friday evening, but you have to work a late shift that cannot be changed. Call your friend to explain and suggest another way to support them.',
    keyPoints: ['Congratulate your friend on the exhibition', 'Explain that you have a late shift on Friday that cannot be changed', 'Express regret about missing the opening', 'Suggest visiting the exhibition another day or meeting to celebrate'],
    sampleResponse: 'Hi! Congratulations on your exhibition, that is such great news. I am really sorry, but I have to work a late shift on Friday, and I have not been able to swap it with anyone. I am disappointed to miss the opening. Could I come and see the exhibition on Saturday instead? And let me take you out for dinner next week to celebrate properly.',
    prepSeconds: 10,
  },
  {
    id: 's-rts-10',
    taskType: 'speaking-respond-to-situation',
    situation: 'You received your exam results, and one mark seems much lower than you expected. You think there may have been a mistake in adding up the scores. Speak to your lecturer to ask about it.',
    keyPoints: ['Greet the lecturer politely and thank them for their time', 'Explain that one mark is much lower than expected', 'Suggest there may be a mistake in adding up the scores', 'Ask whether the paper can be checked again'],
    sampleResponse: 'Good afternoon, thank you for seeing me. I received my exam results, and the mark for the final exam is quite a bit lower than I expected. When I looked at the paper, I noticed that the section totals do not seem to add up to the final score, so there might be a calculation mistake. Would it be possible to check the paper again? I would really appreciate it.',
    prepSeconds: 10,
  },
]
