import type { ScorePreset, Skill, SkillScores, TaskProfile, TestType } from '../types'

const all = (score: number): SkillScores => ({
  listening: score,
  reading: score,
  writing: score,
  speaking: score,
})

export const SKILL_META: Record<
  Skill,
  { label: string; shortLabel: string; color: string; softColor: string }
> = {
  listening: {
    label: '听力',
    shortLabel: '听',
    color: '#c45b1a',
    softColor: '#fff3e8',
  },
  reading: {
    label: '阅读',
    shortLabel: '读',
    color: '#276fae',
    softColor: '#eaf4fc',
  },
  writing: {
    label: '写作',
    shortLabel: '写',
    color: '#7557b7',
    softColor: '#f1edfb',
  },
  speaking: {
    label: '口语',
    shortLabel: '说',
    color: '#147d78',
    softColor: '#e7f7f4',
  },
}

export const SCORE_PRESETS: readonly ScorePreset[] = [
  {
    id: 'au-superior-2025',
    group: 'australia',
    country: '澳洲移民',
    label: 'Superior English（八炸）',
    testType: 'academic',
    testLabel: 'PTE Academic',
    requirement: '2025-08-07 起：听69｜读70｜写85｜说88',
    officialScores: { listening: 69, reading: 70, writing: 85, speaking: 88 },
    recommendedScores: { listening: 73, reading: 73, writing: 90, speaking: 90 },
    officialScoreMode: 'components',
    note: '训练目标已加入安全余量；具体签证仍需核对对应 visa 页面。',
    sourceLabel: 'Australian Department of Home Affairs',
    sourceUrl:
      'https://immi.homeaffairs.gov.au/help-support/meeting-our-requirements/english-language/superior-english',
    checkedAt: '2026-09-03',
  },
  {
    id: 'ca-clb7',
    group: 'canada',
    country: '加拿大移民',
    label: 'Express Entry｜CLB 7',
    testType: 'core',
    testLabel: 'PTE Core',
    requirement: '最低档起点：听60｜读60｜写69｜说68',
    officialScores: { listening: 60, reading: 60, writing: 69, speaking: 68 },
    recommendedScores: { listening: 65, reading: 65, writing: 74, speaking: 73 },
    officialScoreMode: 'components',
    note: '这是 CLB 7 分数区间的下限；项目资格和 CRS 加分需另行核对。',
    sourceLabel: 'Immigration, Refugees and Citizenship Canada',
    sourceUrl:
      'https://www.canada.ca/en/immigration-refugees-citizenship/services/immigrate-canada/express-entry/documents/language-test.html',
    checkedAt: '2026-09-03',
  },
  {
    id: 'ca-clb9',
    group: 'canada',
    country: '加拿大移民',
    label: 'Express Entry｜CLB 9',
    testType: 'core',
    testLabel: 'PTE Core',
    requirement: '听82｜读78｜写88｜说84',
    officialScores: { listening: 82, reading: 78, writing: 88, speaking: 84 },
    recommendedScores: { listening: 85, reading: 82, writing: 90, speaking: 87 },
    officialScoreMode: 'components',
    note: 'CLB 9 常被用作 Express Entry 的高价值备考档位，但不等于获邀保证。',
    sourceLabel: 'Immigration, Refugees and Citizenship Canada',
    sourceUrl:
      'https://www.canada.ca/en/immigration-refugees-citizenship/services/immigrate-canada/express-entry/documents/language-test.html',
    checkedAt: '2026-09-03',
  },
  {
    id: 'ca-clb10',
    group: 'canada',
    country: '加拿大移民',
    label: 'Express Entry｜CLB 10+',
    testType: 'core',
    testLabel: 'PTE Core',
    requirement: '听89｜读88｜写90｜说89',
    officialScores: { listening: 89, reading: 88, writing: 90, speaking: 89 },
    recommendedScores: { listening: 90, reading: 90, writing: 90, speaking: 90 },
    officialScoreMode: 'components',
    note: '按 IRCC 公布的 CLB 10 及以上最低分生成。',
    sourceLabel: 'Immigration, Refugees and Citizenship Canada',
    sourceUrl:
      'https://www.canada.ca/en/immigration-refugees-citizenship/services/immigrate-canada/express-entry/documents/language-test.html',
    checkedAt: '2026-09-03',
  },
  {
    id: 'uk-student-b1',
    group: 'uk',
    country: '英国签证',
    label: '学生签证｜低于学位 B1',
    testType: 'academic',
    testLabel: 'PTE Academic UKVI',
    requirement: '四项均 43+',
    officialScores: all(43),
    recommendedScores: all(48),
    officialScoreMode: 'components',
    note: '必须按路线选择认可的 SELT；院校可能设置更高要求。',
    sourceLabel: 'Pearson PTE UK visa information',
    sourceUrl: 'https://www.pearsonpte.com/destination-uk/visas/',
    checkedAt: '2026-09-03',
  },
  {
    id: 'uk-b2',
    group: 'uk',
    country: '英国签证',
    label: '学位课程/Skilled Worker｜B2',
    testType: 'academic',
    testLabel: 'PTE Academic UKVI',
    requirement: '四项均 59+',
    officialScores: all(59),
    recommendedScores: all(65),
    officialScoreMode: 'components',
    note: '签证路线及院校可能有额外条件；申请前必须核对 GOV.UK 和 CAS。',
    sourceLabel: 'Pearson PTE UK visa information',
    sourceUrl: 'https://www.pearsonpte.com/destination-uk/visas/',
    checkedAt: '2026-09-03',
  },
  {
    id: 'nz-skilled-principal',
    group: 'new-zealand',
    country: '新西兰移民',
    label: '技术类居民签证｜主申请人',
    testType: 'academic',
    testLabel: 'PTE Academic',
    requirement: '官方要求总分 58+',
    officialScores: all(58),
    recommendedScores: all(63),
    officialScoreMode: 'overall',
    note: '官方公布的是总分门槛、并非四项各 58；四项 63 仅作为均衡训练目标。',
    sourceLabel: 'Immigration New Zealand',
    sourceUrl:
      'https://www.immigration.govt.nz/process-to-apply/applying-for-a-visa/providing-evidence-and-documents-to-support-your-visa-application/english-language-requirements/english-language-requirements-for-skilled-residence-visas/',
    checkedAt: '2026-09-03',
  },
  {
    id: 'nz-skilled-family',
    group: 'new-zealand',
    country: '新西兰移民',
    label: '技术类居民签证｜配偶/16+子女',
    testType: 'academic',
    testLabel: 'PTE Academic',
    requirement: '官方要求总分 36+',
    officialScores: all(36),
    recommendedScores: all(43),
    officialScoreMode: 'overall',
    note: '官方公布的是总分门槛；家属也可能选择购买英语课程。',
    sourceLabel: 'Immigration New Zealand',
    sourceUrl:
      'https://www.immigration.govt.nz/process-to-apply/applying-for-a-visa/providing-evidence-and-documents-to-support-your-visa-application/english-language-requirements/english-language-requirements-for-skilled-residence-visas/',
    checkedAt: '2026-09-03',
  },
  ...[58, 65, 79].map((score): ScorePreset => ({
    id: `university-${score}`,
    group: 'university',
    country: '大学申请',
    label: `常见目标档｜${score}`,
    testType: 'academic',
    testLabel: 'PTE Academic',
    requirement: `计划目标：四项 ${score}`,
    officialScores: all(score),
    recommendedScores: all(Math.min(90, score + 3)),
    officialScoreMode: 'guidance',
    note: '这不是统一录取线。请以目标大学、课程和入学年份页面为准，并可手动修改四项。',
    sourceLabel: 'Pearson PTE institution guidance',
    sourceUrl: 'https://www.pearsonpte.com/pte-academic/scoring/understand-your-score',
    checkedAt: '2026-09-03',
  })),
]

export const ACADEMIC_TASKS: readonly TaskProfile[] = [
  {
    id: 'di',
    label: 'Describe Image',
    shortLabel: 'DI',
    primarySkill: 'speaking',
    skillWeights: { speaking: 31 },
    minutesPerItem: 3,
    basePriority: 10,
    standard: '内容覆盖关键关系；发音/流利度稳定在高档',
  },
  {
    id: 'sgd',
    label: 'Summarize Group Discussion',
    shortLabel: 'SGD',
    primarySkill: 'speaking',
    skillWeights: { speaking: 19, listening: 20 },
    minutesPerItem: 7,
    basePriority: 9,
    standard: '抓住各方观点、关系和结论；表达连贯',
  },
  {
    id: 'rs',
    label: 'Repeat Sentence',
    shortLabel: 'RS',
    primarySkill: 'speaking',
    skillWeights: { speaking: 16, listening: 17 },
    minutesPerItem: 1,
    basePriority: 10,
    standard: '内容尽量 70%+；节奏连续，不因纠错停顿',
  },
  {
    id: 'rl',
    label: 'Retell Lecture',
    shortLabel: 'RL',
    primarySkill: 'speaking',
    skillWeights: { speaking: 13, listening: 13 },
    minutesPerItem: 5,
    basePriority: 8,
    standard: '主旨、关键要点与关系完整',
  },
  {
    id: 'rts',
    label: 'Respond to a Situation',
    shortLabel: 'RTS',
    primarySkill: 'speaking',
    skillWeights: { speaking: 13 },
    minutesPerItem: 3,
    basePriority: 8,
    standard: '回应目的完整；语气和场景匹配',
  },
  {
    id: 'ra',
    label: 'Read Aloud',
    shortLabel: 'RA',
    primarySkill: 'speaking',
    skillWeights: { speaking: 9 },
    minutesPerItem: 2,
    basePriority: 7,
    standard: '发音清楚；意群、重音和速度稳定',
  },
  {
    id: 'we',
    label: 'Write Essay',
    shortLabel: 'WE',
    primarySkill: 'writing',
    skillWeights: { writing: 31 },
    minutesPerItem: 25,
    basePriority: 8,
    standard: '切题、结构清楚；200–300 词',
  },
  {
    id: 'swt',
    label: 'Summarize Written Text',
    shortLabel: 'SWT',
    primarySkill: 'writing',
    skillWeights: { writing: 28, reading: 23 },
    minutesPerItem: 12,
    basePriority: 9,
    standard: '单句 5–75 词；主旨与逻辑准确',
  },
  {
    id: 'wfd',
    label: 'Write from Dictation',
    shortLabel: 'WFD',
    primarySkill: 'writing',
    skillWeights: { writing: 23, listening: 13 },
    minutesPerItem: 1,
    basePriority: 10,
    standard: '单词正确率 98%–100%',
  },
  {
    id: 'sst',
    label: 'Summarize Spoken Text',
    shortLabel: 'SST',
    primarySkill: 'writing',
    skillWeights: { writing: 18, listening: 10 },
    minutesPerItem: 12,
    basePriority: 9,
    standard: '50–70 词；信息点与语言质量稳定',
  },
  {
    id: 'rfib',
    label: 'Reading Fill in the Blanks',
    shortLabel: 'FIB',
    primarySkill: 'reading',
    skillWeights: { reading: 25 },
    minutesPerItem: 3,
    basePriority: 9,
    standard: '按空正确率 75%+',
  },
  {
    id: 'fibdd',
    label: 'Reading & Writing Fill in the Blanks',
    shortLabel: 'FIBDD',
    primarySkill: 'reading',
    skillWeights: { reading: 20 },
    minutesPerItem: 3,
    basePriority: 9,
    standard: '按空正确率 70%+',
  },
  {
    id: 'ro',
    label: 'Re-order Paragraphs',
    shortLabel: 'RO',
    primarySkill: 'reading',
    skillWeights: { reading: 9 },
    minutesPerItem: 4,
    basePriority: 6,
    standard: '相邻组合正确率 70%+',
  },
  {
    id: 'hiw',
    label: 'Highlight Incorrect Words',
    shortLabel: 'HIW',
    primarySkill: 'listening',
    skillWeights: { reading: 13, listening: 8 },
    minutesPerItem: 3,
    basePriority: 7,
    standard: '识别率 85%+；控制误点',
  },
  {
    id: 'asq',
    label: 'Answer Short Question',
    shortLabel: 'ASQ',
    primarySkill: 'speaking',
    skillWeights: { listening: 4 },
    minutesPerItem: 1,
    basePriority: 4,
    standard: '题库正确率 80%+',
  },
]

export const CORE_TASKS: readonly TaskProfile[] = [
  {
    id: 'core-ra',
    label: 'Read Aloud',
    shortLabel: 'RA',
    primarySkill: 'speaking',
    skillWeights: { reading: 1, speaking: 1 },
    minutesPerItem: 2,
    basePriority: 8,
    standard: '内容准确；发音与流利度稳定',
  },
  {
    id: 'core-rs',
    label: 'Repeat Sentence',
    shortLabel: 'RS',
    primarySkill: 'speaking',
    skillWeights: { listening: 1, speaking: 1 },
    minutesPerItem: 1,
    basePriority: 10,
    standard: '按原顺序复述尽可能多的词',
  },
  {
    id: 'core-di',
    label: 'Describe Image',
    shortLabel: 'DI',
    primarySkill: 'speaking',
    skillWeights: { speaking: 1 },
    minutesPerItem: 3,
    basePriority: 9,
    standard: '覆盖关键元素、关系和结论',
  },
  {
    id: 'core-rts',
    label: 'Respond to a Situation',
    shortLabel: 'RTS',
    primarySkill: 'speaking',
    skillWeights: { speaking: 1 },
    minutesPerItem: 3,
    basePriority: 9,
    standard: '功能、语气和礼貌程度符合场景',
  },
  {
    id: 'core-asq',
    label: 'Answer Short Question',
    shortLabel: 'ASQ',
    primarySkill: 'speaking',
    skillWeights: { listening: 1, speaking: 1 },
    minutesPerItem: 1,
    basePriority: 5,
    standard: '使用恰当词汇简短准确作答',
  },
  {
    id: 'core-swt',
    label: 'Summarize Written Text',
    shortLabel: 'SWT',
    primarySkill: 'writing',
    skillWeights: { reading: 1, writing: 1 },
    minutesPerItem: 10,
    basePriority: 9,
    standard: '25–50 词；主旨、语法和词汇准确',
  },
  {
    id: 'core-email',
    label: 'Write Email',
    shortLabel: 'Email',
    primarySkill: 'writing',
    skillWeights: { writing: 1 },
    minutesPerItem: 15,
    basePriority: 10,
    standard: '30–140 词；覆盖任务并符合邮件规范',
  },
  {
    id: 'core-rwfib',
    label: 'Reading & Writing Fill in the Blanks',
    shortLabel: 'R&W FIB',
    primarySkill: 'reading',
    skillWeights: { reading: 1, writing: 1 },
    minutesPerItem: 3,
    basePriority: 10,
    standard: '搭配、语法和上下文同时判断',
  },
  {
    id: 'core-ro',
    label: 'Re-order Paragraphs',
    shortLabel: 'RO',
    primarySkill: 'reading',
    skillWeights: { reading: 1 },
    minutesPerItem: 4,
    basePriority: 7,
    standard: '优先建立确定的相邻逻辑链',
  },
  {
    id: 'core-rfib',
    label: 'Reading Fill in the Blanks',
    shortLabel: 'FIB',
    primarySkill: 'reading',
    skillWeights: { reading: 1 },
    minutesPerItem: 3,
    basePriority: 9,
    standard: '按空复盘词义和固定搭配',
  },
  {
    id: 'core-sst',
    label: 'Summarize Spoken Text',
    shortLabel: 'SST',
    primarySkill: 'listening',
    skillWeights: { listening: 1, writing: 1 },
    minutesPerItem: 12,
    basePriority: 9,
    standard: '主旨与关键细节完整，语言简洁',
  },
  {
    id: 'core-lfib',
    label: 'Listening Fill in the Blanks',
    shortLabel: 'L-FIB',
    primarySkill: 'listening',
    skillWeights: { listening: 1, writing: 1 },
    minutesPerItem: 3,
    basePriority: 8,
    standard: '拼写和词形准确',
  },
  {
    id: 'core-hiw',
    label: 'Highlight Incorrect Words',
    shortLabel: 'HIW',
    primarySkill: 'listening',
    skillWeights: { listening: 1, reading: 1 },
    minutesPerItem: 3,
    basePriority: 7,
    standard: '控制误点并保持跟读定位',
  },
  {
    id: 'core-wfd',
    label: 'Write from Dictation',
    shortLabel: 'WFD',
    primarySkill: 'listening',
    skillWeights: { listening: 1, writing: 1 },
    minutesPerItem: 1,
    basePriority: 10,
    standard: '内容词、功能词和拼写完整',
  },
]

export function getPreset(id: string) {
  return SCORE_PRESETS.find((preset) => preset.id === id) ?? SCORE_PRESETS[0]
}

export function getTasks(testType: TestType) {
  return testType === 'core' ? CORE_TASKS : ACADEMIC_TASKS
}
