export const FEATURE_CATEGORIES = [
  {
    id: 'today',
    label: '今天',
    icon: '☀️',
    description: '把今天的小事过成值得记住的一天',
  },
  {
    id: 'memories',
    label: '回忆记录',
    icon: '📷',
    description: '收好照片、文字和一路走来的片段',
  },
  {
    id: 'plans',
    label: '一起计划',
    icon: '🗓️',
    description: '把想做的事，一件件变成共同经历',
  },
  {
    id: 'sweet',
    label: '甜蜜互动',
    icon: '💞',
    description: '聊天、留言，也继续发现彼此',
  },
  {
    id: 'play',
    label: '游戏与创作',
    icon: '🎮',
    description: '来一局小游戏，或者一起创造点什么',
  },
  {
    id: 'mine',
    label: '我的',
    icon: '👤',
    description: '管理个人空间和共同使用偏好',
  },
] as const

export type FeatureCategoryId = (typeof FEATURE_CATEGORIES)[number]['id']

export interface FeatureDefinition {
  name: string
  path: string
  icon: string
  description: string
  category: FeatureCategoryId
  showOnHome: boolean
  showInNavigation: boolean
  quickAccessOrder?: number
  mobileNavOrder?: number
  keywords?: readonly string[]
  relatedRoutes?: readonly string[]
}

/**
 * 所有可直接访问的页面都在这里登记。房间详情页是对应游戏的上下文路由，
 * 因此通过 relatedRoutes 归入同一功能，而登录页不属于产品导航。
 */
export const featureRegistry: readonly FeatureDefinition[] = [
  {
    name: '首页',
    path: '/',
    icon: '🏠',
    description: '回到我们的小世界',
    category: 'today',
    showOnHome: false,
    showInNavigation: true,
    keywords: ['主页', '小世界'],
  },
  {
    name: '每日签到',
    path: '/check-in',
    icon: '💖',
    description: '记录今天的小确幸',
    category: 'today',
    showOnHome: true,
    showInNavigation: true,
    quickAccessOrder: 4,
    keywords: ['打卡'],
  },
  {
    name: '今晚吃什么',
    path: '/food',
    icon: '🍜',
    description: '把选择困难交给美食决策器',
    category: 'today',
    showOnHome: true,
    showInNavigation: true,
    quickAccessOrder: 1,
    keywords: ['吃饭', '美食', '决定'],
  },
  {
    name: '心情追踪',
    path: '/mood-tracker',
    icon: '😊',
    description: '记下每天的心情变化',
    category: 'today',
    showOnHome: true,
    showInNavigation: true,
    keywords: ['情绪'],
  },
  {
    name: '每日挑战',
    path: '/daily-challenge',
    icon: '📋',
    description: '完成今天的爱的小任务',
    category: 'today',
    showOnHome: true,
    showInNavigation: true,
    keywords: ['任务'],
  },
  {
    name: '星座运势',
    path: '/horoscope',
    icon: '⭐',
    description: '看看两个人今天的运势',
    category: 'today',
    showOnHome: false,
    showInNavigation: true,
    keywords: ['星座'],
  },
  {
    name: '我们的相册',
    path: '/photos',
    icon: '📸',
    description: '收藏每一个美好瞬间',
    category: 'memories',
    showOnHome: true,
    showInNavigation: true,
    quickAccessOrder: 3,
    mobileNavOrder: 2,
    keywords: ['照片', '照片墙'],
  },
  {
    name: '恋爱日记',
    path: '/diary',
    icon: '📖',
    description: '写下生活里的甜蜜片段',
    category: 'memories',
    showOnHome: true,
    showInNavigation: true,
    keywords: ['文字', '记录'],
  },
  {
    name: '重要纪念日',
    path: '/anniversaries',
    icon: '💝',
    description: '记住每一个特别的日子',
    category: 'memories',
    showOnHome: true,
    showInNavigation: true,
    keywords: ['周年', '生日'],
  },
  {
    name: '穿搭记录',
    path: '/outfit-records',
    icon: '👔',
    description: '保存喜欢的穿搭和搭配',
    category: 'memories',
    showOnHome: false,
    showInNavigation: true,
    keywords: ['衣服', '搭配'],
  },
  {
    name: 'PTE 备考计划',
    path: '/pte-plan',
    icon: '🎓',
    description: '按目标分数和考试日期生成逐日练习计划',
    category: 'plans',
    showOnHome: true,
    showInNavigation: true,
    keywords: ['PTE', '英语', '考试', '移民', '留学', '备考'],
  },
  {
    name: '共享日程',
    path: '/schedule',
    icon: '📅',
    description: '安排约会和两个人的待办',
    category: 'plans',
    showOnHome: true,
    showInNavigation: true,
    quickAccessOrder: 5,
    mobileNavOrder: 3,
    keywords: ['日历', '约会', '计划'],
  },
  {
    name: '时光计时器',
    path: '/countdown',
    icon: '⏰',
    description: '倒数期待，也累计幸福',
    category: 'plans',
    showOnHome: true,
    showInNavigation: true,
    keywords: ['倒计时', '正计时'],
  },
  {
    name: '心愿清单',
    path: '/wishlist',
    icon: '✨',
    description: '一起收集和完成愿望',
    category: 'plans',
    showOnHome: true,
    showInNavigation: true,
    keywords: ['愿望'],
  },
  {
    name: '100件想做的事',
    path: '/bucket-list',
    icon: '💑',
    description: '把爱情任务一件件打勾',
    category: 'plans',
    showOnHome: false,
    showInNavigation: true,
    keywords: ['愿望桶', '清单'],
  },
  {
    name: '时光胶囊',
    path: '/time-capsule',
    icon: '🎁',
    description: '给未来的我们留一封信',
    category: 'plans',
    showOnHome: true,
    showInNavigation: true,
    keywords: ['未来', '信'],
  },
  {
    name: '共同账本',
    path: '/expenses',
    icon: '💰',
    description: '记录两个人的共同花销',
    category: 'plans',
    showOnHome: false,
    showInNavigation: true,
    keywords: ['花费', '支出', '记账'],
  },
  {
    name: '情侣契约书',
    path: '/love-contract',
    icon: '📜',
    description: '写下属于两个人的约定',
    category: 'plans',
    showOnHome: false,
    showInNavigation: true,
    keywords: ['约定', '合同'],
  },
  {
    name: '情侣聊天室',
    path: '/chat',
    icon: '💬',
    description: '实时聊天，随时传情',
    category: 'sweet',
    showOnHome: true,
    showInNavigation: true,
    quickAccessOrder: 2,
    mobileNavOrder: 1,
    keywords: ['消息', '聊天'],
  },
  {
    name: '甜蜜留言板',
    path: '/notes',
    icon: '💌',
    description: '留下想对对方说的话',
    category: 'sweet',
    showOnHome: true,
    showInNavigation: true,
    quickAccessOrder: 6,
    keywords: ['留言', '便签'],
  },
  {
    name: '情话生成器',
    path: '/love-quotes',
    icon: '💕',
    description: '每天抽一句甜蜜情话',
    category: 'sweet',
    showOnHome: true,
    showInNavigation: true,
    keywords: ['情话', '句子'],
  },
  {
    name: '土味情话',
    path: '/sweet-words',
    icon: '🍬',
    description: '收藏甜到齁的情话',
    category: 'sweet',
    showOnHome: false,
    showInNavigation: true,
    keywords: ['情话'],
  },
  {
    name: '情侣问答',
    path: '/couple-quiz',
    icon: '🤔',
    description: '用问题继续了解彼此',
    category: 'sweet',
    showOnHome: true,
    showInNavigation: true,
    keywords: ['默契', '问题'],
  },
  {
    name: '默契度测试',
    path: '/compatibility-test',
    icon: '💗',
    description: '测测两个人有多合拍',
    category: 'sweet',
    showOnHome: false,
    showInNavigation: true,
    keywords: ['测试', '配对'],
  },
  {
    name: '制作情书',
    path: '/love-letter',
    icon: '✉️',
    description: '创作一封专属浪漫情书',
    category: 'sweet',
    showOnHome: false,
    showInNavigation: true,
    keywords: ['信', '情书'],
  },
  {
    name: '塔罗牌占卜',
    path: '/tarot',
    icon: '🔮',
    description: '抽一张牌，看看恋爱指引',
    category: 'sweet',
    showOnHome: false,
    showInNavigation: true,
    keywords: ['占卜', '运势'],
  },
  {
    name: '五子棋',
    path: '/gomoku',
    icon: '⚫',
    description: '来一场甜蜜的黑白对决',
    category: 'play',
    showOnHome: true,
    showInNavigation: true,
    relatedRoutes: ['/gomoku/[id]'],
    keywords: ['棋'],
  },
  {
    name: '欢乐麻将',
    path: '/mahjong',
    icon: '🀄',
    description: '开一桌轻松的双人牌局',
    category: 'play',
    showOnHome: true,
    showInNavigation: true,
    relatedRoutes: ['/mahjong/[id]'],
    keywords: ['牌局'],
  },
  {
    name: '石头剪刀布',
    path: '/rock-paper-scissors',
    icon: '✊',
    description: '三秒决定今天谁更走运',
    category: 'play',
    showOnHome: false,
    showInNavigation: true,
    keywords: ['猜拳'],
  },
  {
    name: '真心话大冒险',
    path: '/truth-or-dare',
    icon: '🎲',
    description: '用有趣问题增进了解',
    category: 'play',
    showOnHome: true,
    showInNavigation: true,
    keywords: ['真心话', '大冒险'],
  },
  {
    name: '猜猜我画的',
    path: '/drawing',
    icon: '🎨',
    description: '画出来，让对方来猜',
    category: 'play',
    showOnHome: true,
    showInNavigation: true,
    keywords: ['涂鸦', '画画'],
  },
  {
    name: '记忆翻牌',
    path: '/memory-game',
    icon: '🃏',
    description: '一起挑战短时记忆力',
    category: 'play',
    showOnHome: true,
    showInNavigation: true,
    keywords: ['翻牌'],
  },
  {
    name: '情侣配对',
    path: '/matching-game',
    icon: '🧩',
    description: '找到所有成双成对的物品',
    category: 'play',
    showOnHome: false,
    showInNavigation: true,
    keywords: ['配对游戏'],
  },
  {
    name: '装扮小人',
    path: '/dress-up',
    icon: '🎀',
    description: '搭配专属的虚拟形象',
    category: 'play',
    showOnHome: false,
    showInNavigation: true,
    keywords: ['换装'],
  },
  {
    name: '颜色性格测试',
    path: '/color-test',
    icon: '🌈',
    description: '看看颜色里的恋爱风格',
    category: 'play',
    showOnHome: false,
    showInNavigation: true,
    keywords: ['性格', '测试'],
  },
  {
    name: '接住爱心',
    path: '/catch-heart',
    icon: '💗',
    description: '接住从天而降的爱心',
    category: 'play',
    showOnHome: false,
    showInNavigation: true,
    keywords: ['小游戏'],
  },
  {
    name: '雷霆战机',
    path: '/love-survivor',
    icon: '✈️',
    description: '在竖版战场坚持到最后',
    category: 'play',
    showOnHome: false,
    showInNavigation: true,
    keywords: ['飞行', '射击'],
  },
  {
    name: '割草大作战',
    path: '/grass-cutter',
    icon: '🧑‍🌾',
    description: '自动攻击，努力存活五分钟',
    category: 'play',
    showOnHome: false,
    showInNavigation: true,
    keywords: ['生存'],
  },
  {
    name: '表情包大乱斗',
    path: '/emoji-battle',
    icon: '🎴',
    description: '选卡对战，看谁的表情更强',
    category: 'play',
    showOnHome: false,
    showInNavigation: true,
    keywords: ['表情', '卡牌'],
  },
  {
    name: '情侣飞行棋',
    path: '/board-game',
    icon: '🎲',
    description: '掷骰子，一起走完棋盘',
    category: 'play',
    showOnHome: false,
    showInNavigation: true,
    keywords: ['棋盘', '骰子'],
  },
  {
    name: '梦境长安',
    path: '/dream-journey',
    icon: '⚔️',
    description: '探索长安，体验东方幻想回合冒险',
    category: 'play',
    showOnHome: true,
    showInNavigation: true,
    keywords: ['RPG', '回合制', '西游', '冒险'],
  },
  {
    name: '梦幻西游网页版',
    path: '/fantasy-westward-journey',
    icon: '🐒',
    description: '在站内打开网易官方网页游戏',
    category: 'play',
    showOnHome: true,
    showInNavigation: true,
    keywords: ['梦幻西游', '网易', 'H5', '页游'],
  },
  {
    name: '爱情骰子',
    path: '/love-dice',
    icon: '🎯',
    description: '选择困难时就交给骰子',
    category: 'play',
    showOnHome: false,
    showInNavigation: true,
    keywords: ['决定', '随机'],
  },
  {
    name: '个人资料',
    path: '/profile',
    icon: '👤',
    description: '查看和整理个人信息',
    category: 'mine',
    showOnHome: true,
    showInNavigation: true,
    keywords: ['头像', '昵称'],
  },
  {
    name: '个人设置',
    path: '/settings',
    icon: '⚙️',
    description: '调整头像、昵称和个性签名',
    category: 'mine',
    showOnHome: true,
    showInNavigation: true,
    keywords: ['设置', '偏好'],
  },
  {
    name: '共享音乐',
    path: '/music-player',
    icon: '🎵',
    description: '一起听歌，分享浪漫时刻',
    category: 'mine',
    showOnHome: true,
    showInNavigation: true,
    keywords: ['播放器', '歌曲'],
  },
  {
    name: '情侣书架',
    path: '/novels',
    icon: '📚',
    description: '一起阅读和分享故事',
    category: 'mine',
    showOnHome: false,
    showInNavigation: true,
    keywords: ['小说', '阅读'],
  },
  {
    name: '功能申请箱',
    path: '/feature-requests',
    icon: '💡',
    description: '提交想要的新功能和建议',
    category: 'mine',
    showOnHome: false,
    showInNavigation: true,
    keywords: ['反馈', '建议'],
  },
]

export const navigationFeatures = featureRegistry.filter((feature) => feature.showInNavigation)

export const homeFeatures = featureRegistry.filter((feature) => feature.showOnHome)

export const quickAccessFeatures = featureRegistry
  .filter((feature) => feature.quickAccessOrder !== undefined)
  .sort((a, b) => (a.quickAccessOrder ?? 0) - (b.quickAccessOrder ?? 0))

export const mobileNavigationFeatures = featureRegistry
  .filter((feature) => feature.mobileNavOrder !== undefined)
  .sort((a, b) => (a.mobileNavOrder ?? 0) - (b.mobileNavOrder ?? 0))

export function isFeaturePathActive(feature: FeatureDefinition, pathname: string) {
  if (feature.path === '/') return pathname === '/'

  return pathname === feature.path || pathname.startsWith(`${feature.path}/`)
}
